name: The Film Dream Productions
analytics: {}
github: true
description: Producing Stories that Matter
author:
  name: The Film Dream Productions
  url: 'http://thefilmdream.com'
  email: thefilmdream@icloud.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 1
color:
  lightness: 0.4802867
  brandColors:
    - '#FFFFFF'
    - '#C13322'
    - '#030303'
    - '#585858'
    - '#E2A5A4'
  saturation: 0.4928315
  brandStrength: 0.781362
  rhythmicContrast: 0.4820789
content_rating:
  adult: false
typography_spectrum: 0.7688172
opengraph: {}
title: The Film Dream Productions
